export default {
  namespaced: true,
  state: {
    offers: {
      category: [
        "Animador 3D",
        "Alfarería",
        "Artesanía",
        "Cantautor",
        "Cine",
        "Comercio Electrónico",
        "Creador de contenido digital",
        "Danza",
        "Deporte",
        "Desarrollo de software",
        "Diseño gráfico",
        "Diseño de moda",
        "Dramatización teatral",
        "Escultura",
        "Fotografía",
        "Guion",
        "Humor",
        "Ilustración",
        "Interpretación actoral",
        "Literatura",
        "Manualidad",
        "Marketing digital",
        "Música instrumental",
        "Narrativa",
        "Naturaleza",
        "Poesía",
        "Posicionamiento SEO",
        "Programación",
        "Tecnologías de la comunicación",
        "Tecnologías web",
        "Vídeo",
        "Videojuegos",
      ],
      duration: [
        "Contrato por obra",
        "Formación y prácticas",
        "Indefinido",
        "Tiempo completo",
        "Tiempo parcial",
      ],
      place: [
        "Tenerife",
        "La Gomera",
        "La Palma",
        "El Hierro",
        "Gran Canaria",
        "Fuerteventura",
        "Lanzarote",
        "La Graciosa",
      ],
    },
    projects: {
      category: [
        "Animador 3D",
        "Alfarería",
        "Artesanía",
        "Cantautor",
        "Cine",
        "Comercio Electrónico",
        "Creador de contenido digital",
        "Danza",
        "Deporte",
        "Desarrollo de software",
        "Diseño gráfico",
        "Diseño de moda",
        "Dramatización teatral",
        "Escultura",
        "Fotografía",
        "Guion",
        "Humor",
        "Ilustración",
        "Interpretación actoral",
        "Literatura",
        "Manualidad",
        "Marketing digital",
        "Música instrumental",
        "Narrativa",
        "Naturaleza",
        "Poesía",
        "Posicionamiento SEO",
        "Programación",
        "Tecnologías de la comunicación",
        "Tecnologías web",
        "Vídeo",
        "Videojuegos",
      ],
      duration: [
        "Abril 2021",
        "Mayo 2021",
        "Junio 2021",
        "Julio 2021",
        "Agosto 2021",
        "Septiembre 2021",
        "Octubre 2021",
        "Noviembre 2021",
        "Diciembre 2021",
        "Enero 2022",
        "Febrero 2022",
        "Marzo 2022",
        "Abril 2022",
        "Mayo 2022",
        "Junio 2022",
        "Julio 2022",
        "Agosto 2022",
        "Septiembre 2022",
        "Octubre 2022",
        "Noviembre 2022",
        "Diciembre 2022",
      ],
      place: [
        "Tenerife",
        "La Gomera",
        "La Palma",
        "El Hierro",
        "Gran Canaria",
        "Fuerteventura",
        "Lanzarote",
        "La Graciosa",
      ],
    }
  },
  getters: {
    getOffers(state) {
      return state.offers;
    },
    getProjects(state) {
      return state.projects;
    }
  },
};
